//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//LOADING
export const LOGIN_CHECK_REQUEST = "LOGIN_CHECK_REQUEST";
export const LOGIN_CHECK_SUCCESS = "LOGIN_CHECK_SUCCESS";
export const LOGIN_CHECK_FAILURE = "LOGIN_CHECK_FAILURE";

//BOARD WRITE
export const BOARD_WRITE_REQUEST = "BOARD_WRITE_REQUEST";
export const BOARD_WRITE_SUCCESS = "BOARD_WRITE_SUCCESS";
export const BOARD_WRITE_FAILURE = "BOARD_WRITE_FAILURE";

//BOARD DETAIL
export const BOARD_DETAIL_REQUEST = "BOARD_DETAIL_REQUEST";
export const BOARD_DETAIL_SUCCESS = "BOARD_DETAIL_SUCCESS";
export const BOARD_DETAIL_FAILURE = "BOARD_DETAIL_FAILURE";

//BOARD STATUS
export const BOARD_STATUS_REQUEST = "BOARD_STATUS_REQUEST";
export const BOARD_STATUS_SUCCESS = "BOARD_STATUS_SUCCESS";
export const BOARD_STATUS_FAILURE = "BOARD_STATUS_FAILURE";
