//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//LOADING
export const LOGIN_CHECK_REQUEST = "LOGIN_CHECK_REQUEST";
export const LOGIN_CHECK_SUCCESS = "LOGIN_CHECK_SUCCESS";
export const LOGIN_CHECK_FAILURE = "LOGIN_CHECK_FAILURE";

//BOARD WRITE
export const BOARD_WRITE_REQUEST = "BOARD_WRITE_REQUEST";
export const BOARD_WRITE_SUCCESS = "BOARD_WRITE_SUCCESS";
export const BOARD_WRITE_FAILURE = "BOARD_WRITE_FAILURE";

//BOARD DETAIL
export const BOARD_DETAIL_REQUEST = "BOARD_DETAIL_REQUEST";
export const BOARD_DETAIL_SUCCESS = "BOARD_DETAIL_SUCCESS";
export const BOARD_DETAIL_FAILURE = "BOARD_DETAIL_FAILURE";

//BOARD DELETE
export const BOARD_DELETE_REQUEST = "BOARD_DELETE_REQUEST";
export const BOARD_DELETE_SUCCESS = "BOARD_DELETE_SUCCESS";
export const BOARD_DELETE_FAILURE = "BOARD_DELETE_FAILURE";

//BOARD UPDATE
export const BOARD_UPDATE_REQUEST = "BOARD_UPDATE_REQUEST";
export const BOARD_UPDATE_SUCCESS = "BOARD_UPDATE_SUCCESS";
export const BOARD_UPDATE_FAILURE = "BOARD_UPDATE_FAILURE";

//IMAGE DELETE
export const IMAGE_DELETE_REQUEST = "IMAGE_DELETE_REQUEST";
export const IMAGE_DELETE_SUCCESS = "IMAGE_DELETE_SUCCESS";
export const IMAGE_DELETE_FAILURE = "IMAGE_DELETE_FAILURE";

//BOARD STATUS
export const BOARD_STATUS_REQUEST = "BOARD_STATUS_REQUEST";
export const BOARD_STATUS_SUCCESS = "BOARD_STATUS_SUCCESS";
export const BOARD_STATUS_FAILURE = "BOARD_STATUS_FAILURE";

//COMMENT GET
export const COMMENT_GET_REQUEST = "COMMENT_GET_REQUEST";
export const COMMENT_GET_SUCCESS = "COMMENT_GET_SUCCESS";
export const COMMENT_GET_FAILURE = "COMMENT_GET_FAILURE";

//BOARD HIT
export const BOARD_HIT_REQUEST = "BOARD_HIT_REQUEST";
export const BOARD_HIT_SUCCESS = "BOARD_HIT_SUCCESS";
export const BOARD_HIT_FAILURE = "BOARD_HIT_FAILURE";

//COMMENT UPLOAD
export const COMMENT_UPLOAD_REQUEST = "COMMENT_UPLOAD_REQUEST";
export const COMMENT_UPLOAD_SUCCESS = "COMMENT_UPLOAD_SUCCESSE";
export const COMMENT_UPLOAD_FAILURE = "COMMENT_UPLOAD_FAILURE";

//COMMENT UPDATE
export const COMMENT_UPDATE_REQUEST = "COMMENT_UPDATE_REQUEST";
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESSE";
export const COMMENT_UPDATE_FAILURE = "COMMENT_UPDATE_FAILURE";

//COMMENT UPDATE
export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESSE";
export const COMMENT_DELETE_FAILURE = "COMMENT_DELETE_FAILURE";

//REPLY UPLOAD
export const REPLY_UPLOAD_REQUEST = "REPLY_UPLOAD_REQUEST";
export const REPLY_UPLOAD_SUCCESS = "REPLY_UPLOAD_SUCCESS";
export const REPLY_UPLOAD_FAILURE = "REPLY_UPLOAD_FAILURE";

//TRADE COMMENT GET
export const TRADE_COMMENT_GET_REQUEST = "TRADE_COMMENT_GET_REQUEST";
export const TRADE_COMMENT_GET_SUCCESS = "TRADE_COMMENT_GET_SUCCESS";
export const TRADE_COMMENT_GET_FAILURE = "TRADE_COMMENT_GET_FAILURE";

//TRADE COMPLETE
export const TRADE_COMPLETE_REQUEST = "TRADE_COMPLETE_REQUEST";
export const TRADE_COMPLETE_SUCCESS = "TRADE_COMPLETE_SUCCESS";
export const TRADE_COMPLETE_FAILURE = "TRADE_COMPLETE_FAILURE";

//PROFILE GET
export const PROFILE_GET_REQUEST = "PROFILE_GET_REQUEST";
export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS";
export const PROFILE_GET_FAILURE = "PROFILE_GET_FAILURE";

//PROFILE GET
export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAILURE = "PROFILE_UPDATE_FAILURE";

//PROFILE IMAGE UPDATE
export const PROFILE_IMAGE_UPDATE_REQUEST = "PROFILE_IMAGE_UPDATE_REQUEST";
export const PROFILE_IMAGE_UPDATE_SUCCESS = "PROFILE_IMAGE_UPDATE_SUCCESS";
export const PROFILE_IMAGE_UPDATE_FAILURE = "PROFILE_IMAGE_UPDATE_FAILURE";

//WATCHLIST ADD
export const WATCHLIST_ADD_REQUEST = "WATCHLIST_ADD_REQUEST";
export const WATCHLIST_ADD_SUCCESS = "WATCHLIST_ADD_SUCCESS";
export const WATCHLIST_ADD_FAILURE = "WATCHLIST_ADD_FAILURE";

//WATCHLIST DELETE
export const WATCHLIST_DELETE_REQUEST = "WATCHLIST_DELETE_REQUEST";
export const WATCHLIST_DELETE_SUCCESS = "WATCHLIST_DELETE_SUCCESS";
export const WATCHLIST_DELETE_FAILURE = "WATCHLIST_DELETE_FAILURE";

//NOTIFICATION
export const NOTIFICATION_REQUEST = "NOTIFICATION_REQUEST";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILURE = "NOTIFICATION_FAILURE";

//NOTIFICATION
export const NOTIFICATION_GET_REQUEST = "NOTIFICATION_GET_REQUEST";
export const NOTIFICATION_GET_SUCCESS = "NOTIFICATION_GET_SUCCESS";
export const NOTIFICATION_GET_FAILURE = "NOTIFICATION_GET_FAILURE";

//NOTIFICATION
export const NOTIFICATION_READ_REQUEST = "NOTIFICATION_READ_REQUEST";
export const NOTIFICATION_READ_SUCCESS = "NOTIFICATION_READ_SUCCESS";
export const NOTIFICATION_READ_FAILURE = "NOTIFICATION_READ_FAILURE";
