//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOADING
export const LOGIN_CHECK_REQUEST = "LOGIN_CHECK_REQUEST";
export const LOGIN_CHECK_SUCCESS = "LOGIN_CHECK_SUCCESS";
export const LOGIN_CHECK_FAILURE = "LOADING_FAILURE";
